### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by Lenni009**

### CODE REVIEW

**Comment by Khaoz-Topsy** [comment]
Ah thanks 💪
But those are generated files, the .hbs files are the source 😋

**Comment by Lenni009** [comment]
The test failed when I only edited the hbs file

**Comment by Khaoz-Topsy** [comment]
Weird, well now its sad because of a merge conflict apparently 🤔

I think the change you want to make is on line 243 in index.html.hbs. Not sure about the other change, Github is not showing it to me properly 😅

**Comment by Khaoz-Topsy** [comment]
Ah your fork is 6 commits behind 😋

**Comment by Lenni009** [comment]
give me a minute and I will fix it

**Comment by Lenni009** [comment]
Merge conflict resolved, check running and will probably fail.

**Comment by Lenni009** [comment]
> Ah your fork is 6 commits behind 😋

That's what I get for forking the main branch...

**Comment by Khaoz-Topsy** [comment]
Ah, don't worry about it, it is trying to deploy the change already. The workflow shouldn't trigger on PR 🤔. Future Kurt will figure it out 😂

**Pull request merged**
